### ISSUE TITLE
Use meaningful param names, ex. (first_element, second_element)

### ISSUE THREAD

**Issue by PavelBezpalov** [artemkobets/rubygh#3]
https://github.com/artemkobets/rubygh/blob/5aef5861bd0b4dd0449b312a32064bd60eff3d77/hw1/ch7/ch7_1.rb#L19

**Comment by artemkobets** [comment]
Changed names to more meaningful ones 
https://github.com/artemkobets/rubygh/blob/580f496258eefeae93ee56855973e47d5345af26/hw1/ch7/ch7_1.rb#L19-L63

**Comment by artemkobets** [comment]
Also fixed unneeded global variable $word_arr
https://github.com/artemkobets/rubygh/blob/580f496258eefeae93ee56855973e47d5345af26/hw1/ch7/ch7_1.rb#L68-L74
