### ISSUE TITLE
Google why global variables are dangerous. Avoid using it.

### ISSUE THREAD

**Issue by PavelBezpalov** [artemkobets/rubygh#4]
https://github.com/artemkobets/rubygh/blob/5aef5861bd0b4dd0449b312a32064bd60eff3d77/hw1/ch10/ch10_2.rb#L1

**Comment by artemkobets** [comment]
Wrapped log command into a class, replaced global variables with class instance variables
https://github.com/artemkobets/rubygh/blob/580f496258eefeae93ee56855973e47d5345af26/hw1/ch10/ch10_2.rb

**Comment by artemkobets** [comment]
Also fixed unneeded global variable $word_arr
https://github.com/artemkobets/rubygh/blob/580f496258eefeae93ee56855973e47d5345af26/hw1/ch7/ch7_1.rb#L68-L74

**Comment by artemkobets** [comment]
also replaced block.call with yield in every file (Rubocop warning/Performance)
https://github.com/artemkobets/rubygh/blob/580f496258eefeae93ee56855973e47d5345af26/hw1/ch10/ch10_1.rb#L1-L11
